channels:
- conda-forge
dependencies:
- arxiv
- bibtexparser
- click
- docopt
- gitpython
- numpy
- pytest
- python
- pyyaml
- requests
- setuptools_scm
- sphinx
- sphinx-argparse
- sphinx_rtd_theme
- tqdm
