name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:

  default-shell:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.runs-on }} • x64 ${{ matrix.args }}
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        cache-env: true

    - name: Install library
      run: python -m pip install .

    - name: Run tests
      working-directory: tests
      run: |
        python GbibClean.py
        python journals.py
        python recognise.py
        python reformat.py
        python tex.py
